# Generated by Django 4.1.2 on 2023-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=10)),
                ("username", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=200)),
                ("pincode", models.IntegerField()),
                ("district", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
            ],
        ),
    ]
