# Generated by Django 4.1.2 on 2023-03-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0009_remove_profile_userid"),
        ("credential", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffregistration",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="NoteApp.profile",
                unique=True,
            ),
        ),
    ]
