# Generated by Django 4.1.2 on 2023-03-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credential", "0002_alter_staffregistration_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffregistration", old_name="userid", new_name="businessid",
        ),
    ]
