# Generated by Django 4.1.2 on 2023-03-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credential", "0003_rename_userid_staffregistration_businessid"),
    ]

    operations = [
        migrations.RemoveField(model_name="staffregistration", name="businessid",),
    ]
