# Generated by Django 4.1.2 on 2023-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credential", "0006_stafflogin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stafflogin",
            name="userid",
            field=models.CharField(max_length=200),
        ),
    ]
