# Generated by Django 4.1.2 on 2023-03-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "credential",
            "0009_remove_stafflogin_staffregistration_stafflogin_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Subject", models.CharField(max_length=200)),
                ("Message", models.CharField(max_length=250)),
            ],
        ),
    ]
