# Generated by Django 4.1.2 on 2023-03-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("businessname", models.CharField(max_length=200)),
                ("contact", models.IntegerField()),
                ("address", models.CharField(max_length=200)),
                ("pincode", models.IntegerField()),
            ],
        ),
    ]
