# Generated by Django 4.1.2 on 2023-03-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0002_rename_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="contact", field=models.CharField(max_length=15),
        ),
    ]
