# Generated by Django 4.1.2 on 2023-03-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0004_rename_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="userid",
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
