# Generated by Django 4.1.2 on 2023-03-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0005_profile_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="userid", new_name="businessid",
        ),
    ]
