# Generated by Django 4.1.2 on 2023-03-04 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0006_rename_userid_profile_businessid"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="district",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
