# Generated by Django 4.1.2 on 2023-03-04 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0007_profile_district_profile_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="userid",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
