# Generated by Django 4.1.2 on 2023-03-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0008_profile_userid"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="userid",),
    ]
