# Generated by Django 4.1.2 on 2023-03-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0009_remove_profile_userid"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="businessid",),
    ]
