# Generated by Django 4.1.2 on 2023-03-05 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("NoteApp", "0010_remove_profile_businessid"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="businessid",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
